### ISSUE TITLE
NullPointerException if cache files do not already exist on Ubuntu

### ISSUE THREAD

**Issue by jamesseatter** [jamesseatter/home_measurement_iot_collector#98]
If the cache files already exist the code runs fine, if a new file is required the code throws a NullPointerException 

Caused by: java.lang.NullPointerException: null
        at java.io.File.<init>(File.java:277)
        at eu.seatter.homemeasurement.collector.cache.map.MeasurementCacheMapImpl.flushToFile(MeasurementCacheMapImpl.java:142)
        at eu.seatter.homemeasurement.collector.cache.map.MeasurementCacheMapImpl.add(MeasurementCacheMapImpl.java:63)
        at eu.seatter.homemeasurement.collector.services.cache.MeasurementCacheService.add(MeasurementCacheService.java:27)
        at eu.seatter.homemeasurement.collector.services.CollectorService.run(CollectorService.java:139)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:813)

**Comment by jamesseatter** [comment]
Debugging shows that
File file = new File(CACHE_PATH);
File directory = new File(file.getParent());

file.getParent() returns null, this is a known feature due to CACHE_PATH being a string and the parent not being specifically provided.https://bugs.openjdk.java.net/browse/JDK-8202972

**Comment by jamesseatter** [comment]
The solution split the definition of the cache files in the various application*properties files.
cache.root.path=/home/iot/bin/collector_${spring.profiles.active}/cache
cache.measurement.file=measurement_cache.json
cache.alert.measurement.file=alert_measurement_cache.json
cache.alert.system.file=alert_system_cache.json
cache.mqfailed.measurement.file=mq_failed_measurement_cache.json

Update the code to merge the Path and the File into a single path that can then be used correctly.
